# global config
batch_size: 64
epoch: 100
check_val_every_n_epoch: 10
checkpoint: ./checkpoint
log_dir: ./log

# dataset
path: H:/E_extension/dataset/waterScene
split: train tiny
coordinate_mode: velodyne
preload_offset: -1

# dataloader
full_area: True
template_size: 32
search_size: 256
