# dataset
path: H:/E_extension/dataset/waterScene
dataset: waterscene
point_dim: 8
train_split: train
valid_split: valid
test_split: test
coordinate_mode: velodyne

# dataloader
full_area: True
search_area_offset:
template_offset: 0.3
template_size: 32
search_size: 256
workers: 12

# train
checkpoint: ./checkpoint
batch_size: 64
epoch: 200
pretrain:
optimizer: adam
lr: 0.0001
wd: 0.0001
check_val_every_n_epoch: 1
save_last: True
use_fps: True
normalize_xyz: True

# loss
object_weight: 1.5
box_weight: 0.2
vote_weight: 1.0
seg_weight: 0.2
