# dataset
path: ../dataset/kitti
dataset: kitti
point_dim: 3
train_split: train
valid_split: valid
test_split: test tiny
coordinate_mode: velodyne

# dataloader
full_area: False
rand_distortion_range: 0.3
search_area_offset: 2
template_size: 512
search_size: 1024
workers: 12
box_enlarge_scale: 1.25

# model
use_repSurf: True
backbone: dgn

# train
checkpoint: ./checkpoint
batch_size: 8
epoch: 200
pretrain:
optimizer: adam
lr: 0.001
check_val_every_n_epoch: 1
save_last: True
use_fps: True
normalize_xyz: True

# loss
object_weight: 1.5
box_weight: 0.2
vote_weight: 1.0
seg_weight: 0.2
